export interface SyntaxTheme {
  id: string
  label: string
  /** "dark" themes get a dark code surface, "light" a light one */
  base: "dark" | "light"
  colors: {
    bg: string
    fg: string
    gutter: string
    key: string
    string: string
    number: string
    boolean: string
    null: string
    comment: string
    keyword: string
    func: string
    /** Type / class / interface names. Falls back to `func` when omitted. */
    type?: string
    attr: string
    punctuation: string
    match: string
  }
}

export const SYNTAX_THEMES: SyntaxTheme[] = [
  // Aura Noir family — themes authored by the StructFlow maintainer
  // (https://github.com/jessur2030/aura-noir-theme), mapped to the --syn-* slots.
  {
    id: "aura-noir",
    label: "Aura Noir",
    base: "dark",
    colors: {
      bg: "#14151B",
      fg: "#ABB5C8",
      gutter: "#434B5E",
      key: "#75C3CB",
      string: "#E59E8A",
      number: "#ED926B",
      boolean: "#ED926B",
      null: "#ED926B",
      comment: "#6A9955",
      keyword: "#C2A3FF",
      func: "#69D2AE",
      type: "#EAC57C",
      attr: "#75C3CB",
      punctuation: "#BCC6D8",
      match: "#2B3245",
    },
  },
  {
    id: "aura-noir-modern",
    label: "Aura Noir Modern",
    base: "dark",
    colors: {
      bg: "#14151B",
      fg: "#D4D4D4",
      gutter: "#434B5E",
      key: "#9CDCFE",
      string: "#CE9178",
      number: "#B5CEA8",
      boolean: "#4FC1FF",
      null: "#4FC1FF",
      comment: "#6A9955",
      keyword: "#569CD6",
      func: "#DCDCAA",
      type: "#4EC9B0",
      attr: "#9CDCFE",
      punctuation: "#D4D4D4",
      match: "#2B3245",
    },
  },
  {
    id: "aura-noir-aurora",
    label: "Aura Noir Aurora",
    base: "dark",
    colors: {
      bg: "#14151B",
      fg: "#ABB5C8",
      gutter: "#434B5E",
      key: "#7FC8D0",
      string: "#E5A98A",
      number: "#F0B884",
      boolean: "#F0B884",
      null: "#F0B884",
      comment: "#6A9955",
      keyword: "#45C7D4",
      func: "#6FE0C0",
      type: "#E6D08A",
      attr: "#7FC8D0",
      punctuation: "#BCCAD0",
      match: "#2B3245",
    },
  },
  {
    id: "aura-noir-ember",
    label: "Aura Noir Ember",
    base: "dark",
    colors: {
      bg: "#14151B",
      fg: "#ABB5C8",
      gutter: "#434B5E",
      key: "#9CC8D0",
      string: "#D98E70",
      number: "#F08868",
      boolean: "#F08868",
      null: "#F08868",
      comment: "#6A9955",
      keyword: "#E8A85C",
      func: "#F0C674",
      type: "#7FD8C0",
      attr: "#9CC8D0",
      punctuation: "#CAC2B6",
      match: "#2B3245",
    },
  },
  {
    id: "aura-noir-rose",
    label: "Aura Noir Rose",
    base: "dark",
    colors: {
      bg: "#14151B",
      fg: "#ABB5C8",
      gutter: "#434B5E",
      key: "#85C8D0",
      string: "#E5A98A",
      number: "#F08080",
      boolean: "#F08080",
      null: "#F08080",
      comment: "#6A9955",
      keyword: "#E68FB8",
      func: "#7FD0E0",
      type: "#F0C674",
      attr: "#85C8D0",
      punctuation: "#C8C0CC",
      match: "#2B3245",
    },
  },
  {
    id: "aura-noir-forest",
    label: "Aura Noir Forest",
    base: "dark",
    colors: {
      bg: "#14151B",
      fg: "#ABB5C8",
      gutter: "#434B5E",
      key: "#85C8D0",
      string: "#E5A98A",
      number: "#E0B070",
      boolean: "#E0B070",
      null: "#E0B070",
      comment: "#6A9955",
      keyword: "#4DBE8E",
      func: "#E6C878",
      type: "#5BC8D8",
      attr: "#85C8D0",
      punctuation: "#BAC8C2",
      match: "#2B3245",
    },
  },
  {
    id: "aura-noir-crimson",
    label: "Aura Noir Crimson",
    base: "dark",
    colors: {
      bg: "#14151B",
      fg: "#ABB5C8",
      gutter: "#434B5E",
      key: "#85C8D0",
      string: "#E5A98A",
      number: "#F0B884",
      boolean: "#F0B884",
      null: "#F0B884",
      comment: "#6A9955",
      keyword: "#E06A78",
      func: "#E6C878",
      type: "#5BC8D8",
      attr: "#85C8D0",
      punctuation: "#CCC0C4",
      match: "#2B3245",
    },
  },
  {
    id: "aura-lumen",
    label: "Aura Lumen",
    base: "light",
    colors: {
      bg: "#FBFBFD",
      fg: "#2E3440",
      gutter: "#BCC2D2",
      key: "#2A5A9A",
      string: "#B5523C",
      number: "#1C7E5A",
      boolean: "#0F62C4",
      null: "#0F62C4",
      comment: "#4C8A3F",
      keyword: "#6E4FD0",
      func: "#8A6A1F",
      type: "#1F7A8C",
      attr: "#2A5A9A",
      punctuation: "#4A4F5C",
      match: "#6E4FD033",
    },
  },
  {
    id: "aura-day",
    label: "Aura Day",
    base: "light",
    colors: {
      bg: "#FBFBFD",
      fg: "#2E3440",
      gutter: "#BCC2D2",
      key: "#2A5A9A",
      string: "#B5523C",
      number: "#1C7E5A",
      boolean: "#0F62C4",
      null: "#0F62C4",
      comment: "#4C8A3F",
      keyword: "#1F6FD6",
      func: "#8A6A1F",
      type: "#1F7A8C",
      attr: "#2A5A9A",
      punctuation: "#4A4F5C",
      match: "#1F6FD633",
    },
  },
  {
    id: "vscode-dark",
    label: "VS Code Dark+",
    base: "dark",
    colors: {
      bg: "#1e1e1e",
      fg: "#d4d4d4",
      gutter: "#858585",
      key: "#9cdcfe",
      string: "#ce9178",
      number: "#b5cea8",
      boolean: "#569cd6",
      null: "#569cd6",
      comment: "#6a9955",
      keyword: "#c586c0",
      func: "#dcdcaa",
      type: "#4EC9B0",
      attr: "#9cdcfe",
      punctuation: "#808080",
      match: "#613214",
    },
  },
  {
    id: "vscode-light",
    label: "VS Code Light+",
    base: "light",
    colors: {
      bg: "#ffffff",
      fg: "#1f1f1f",
      gutter: "#999999",
      key: "#0451a5",
      string: "#a31515",
      number: "#098658",
      boolean: "#0000ff",
      null: "#0000ff",
      comment: "#008000",
      keyword: "#af00db",
      func: "#795e26",
      type: "#267F99",
      attr: "#0451a5",
      punctuation: "#7a7a7a",
      match: "#ffe9a8",
    },
  },
  {
    id: "github-dark",
    label: "GitHub Dark",
    base: "dark",
    colors: {
      bg: "#0d1117",
      fg: "#e6edf3",
      gutter: "#6e7681",
      key: "#79c0ff",
      string: "#a5d6ff",
      number: "#79c0ff",
      boolean: "#79c0ff",
      null: "#ff7b72",
      comment: "#8b949e",
      keyword: "#ff7b72",
      func: "#d2a8ff",
      type: "#FFA657",
      attr: "#7ee787",
      punctuation: "#8b949e",
      match: "#3b2e0a",
    },
  },
  {
    id: "github-light",
    label: "GitHub Light",
    base: "light",
    colors: {
      bg: "#ffffff",
      fg: "#1f2328",
      gutter: "#8c959f",
      key: "#0550ae",
      string: "#0a3069",
      number: "#0550ae",
      boolean: "#0550ae",
      null: "#cf222e",
      comment: "#6e7781",
      keyword: "#cf222e",
      func: "#8250df",
      type: "#953800",
      attr: "#116329",
      punctuation: "#6e7781",
      match: "#fff8c5",
    },
  },
  {
    id: "monokai",
    label: "Monokai",
    base: "dark",
    colors: {
      bg: "#272822",
      fg: "#f8f8f2",
      gutter: "#90908a",
      key: "#a6e22e",
      string: "#e6db74",
      number: "#ae81ff",
      boolean: "#ae81ff",
      null: "#ae81ff",
      comment: "#75715e",
      keyword: "#f92672",
      func: "#a6e22e",
      type: "#66D9EF",
      attr: "#66d9ef",
      punctuation: "#f8f8f2",
      match: "#49483e",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    base: "dark",
    colors: {
      bg: "#282a36",
      fg: "#f8f8f2",
      gutter: "#6272a4",
      key: "#8be9fd",
      string: "#f1fa8c",
      number: "#bd93f9",
      boolean: "#bd93f9",
      null: "#bd93f9",
      comment: "#6272a4",
      keyword: "#ff79c6",
      func: "#50fa7b",
      type: "#8BE9FD",
      attr: "#50fa7b",
      punctuation: "#f8f8f2",
      match: "#44475a",
    },
  },
  {
    id: "nord",
    label: "Nord",
    base: "dark",
    colors: {
      bg: "#2e3440",
      fg: "#d8dee9",
      gutter: "#616e88",
      key: "#8fbcbb",
      string: "#a3be8c",
      number: "#b48ead",
      boolean: "#81a1c1",
      null: "#81a1c1",
      comment: "#616e88",
      keyword: "#81a1c1",
      func: "#88c0d0",
      type: "#8FBCBB",
      attr: "#8fbcbb",
      punctuation: "#eceff4",
      match: "#434c5e",
    },
  },
  {
    id: "solarized-light",
    label: "Solarized Light",
    base: "light",
    colors: {
      bg: "#fdf6e3",
      fg: "#586e75",
      gutter: "#93a1a1",
      key: "#268bd2",
      string: "#2aa198",
      number: "#d33682",
      boolean: "#6c71c4",
      null: "#6c71c4",
      comment: "#93a1a1",
      keyword: "#859900",
      func: "#b58900",
      type: "#B58900",
      attr: "#268bd2",
      punctuation: "#657b83",
      match: "#eee8d5",
    },
  },
]

export const DEFAULT_SYNTAX_THEME = "aura-noir"

export function getSyntaxTheme(id: string): SyntaxTheme {
  return SYNTAX_THEMES.find((t) => t.id === id) ?? SYNTAX_THEMES[0]
}

/** Returns CSS custom properties for a theme, to be spread onto a container's style. */
export function syntaxThemeVars(theme: SyntaxTheme): Record<string, string> {
  const c = theme.colors
  return {
    "--syn-bg": c.bg,
    "--syn-fg": c.fg,
    "--syn-gutter": c.gutter,
    "--syn-key": c.key,
    "--syn-string": c.string,
    "--syn-number": c.number,
    "--syn-boolean": c.boolean,
    "--syn-null": c.null,
    "--syn-comment": c.comment,
    "--syn-keyword": c.keyword,
    "--syn-func": c.func,
    "--syn-type": c.type ?? c.func,
    "--syn-attr": c.attr,
    "--syn-punctuation": c.punctuation,
    "--syn-match": c.match,
  }
}
